classdef ApiCode<uint8
	enumeration
		%1个参数为创建，2个为尝试创建
		CreateTiffReader(0)
		DestroyTiffReader(1)
		CreateOmeTiffReader(2)
		DestroyOmeTiffReader(3)
		%创建方法，文件路径，基本参数
		CreateOmeBigTiff5D(4)
		DestroyOmeBigTiff5D(5)
		GetFileName(6)
		SetFileName(7)
		GetSizeX(8)
		SetSizeX(9)
		GetSizeY(10)
		SetSizeY(11)
		GetSizeC(12)
		SetSizeC(13)
		GetSizeZ(14)
		SetSizeZ(15)
		GetSizeT(16)
		SetSizeT(17)
		GetSizeI(18)
		GetDimensionOrder(19)
		SetDimensionOrder(20)
		GetPixelType(21)
		SetPixelType(22)
		%无参数为读全部通道，1个UINT8为读特定通道，1个UINT32数组为写全部通道，(UINT8,UINT32)为写特定通道
		ChannelColor(23)
		BytesPerSample(24)
		GetImageDescription(25)
		SetImageDescription(26)
		ReadPixels3D(27)
		ReadPixels5D(28)
		WritePixels5D(29)
		PixelPointer3D(30)
		PixelPointer5D(31)
	end
end