#pragma once
enum class SampleFormat :UINT16
{
	SAMPLEFORMAT_UINT = 1,
	SAMPLEFORMAT_INT = 2,
	SAMPLEFORMAT_IEEEFP = 3,
	SAMPLEFORMAT_VOID = 4,
	SAMPLEFORMAT_COMPLEXINT = 5,
	SAMPLEFORMAT_COMPLEXIEEEFP = 6,
};