classdef ApiCode<uint8
	enumeration
		%1个参数为创建，2个为尝试创建
		CreateTiffReader(0)
		DestroyTiffReader(1)
		CreateOmeTiffReader(2)
		DestroyOmeTiffReader(3)
		%创建方法，文件路径，基本参数
		CreateOmeBigTiff5D(4)
		DestroyOmeBigTiff5D(5)
		FileName(6)
		SizeX(7)
		SizeY(8)
		SizeC(9)
		SizeZ(10)
		SizeT(11)
		SizeI(12)
		DimensionOrder(13)
		PixelType(14)
		%无参数为读全部通道，1个UINT8为读特定通道，1个UINT32数组为写全部通道，(UINT8,UINT32)为写特定通道
		ChannelColor(15)
		BytesPerSample(16)
		ImageDescription(17)
		ReadPixels3D(18)
		ReadPixels5D(19)
		WritePixels5D(20)
		PixelPointer3D(21)
		PixelPointer5D(22)
		ModifyMultiParameters(23)
	end
end